feat: toggle defer ads
quintype/react-dfp pull request #2
Opened 2021-05-17 07:52 UTC by sivteck

fixes https://github.com/quintype/madrid/issues/3601

2021-05-17 11:55 UTC, EnKrypt requested changes

2021-05-17 11:55 UTC, EnKrypt commented on js/utils.js
> +      }, 2500);
Can the delay amount be made as a variable? Using it as a config value would be good to have.

2021-05-17 11:55 UTC, EnKrypt commented on lib/utils.js
> +  var deferAds = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : true;
```suggestion
  var limitedAds = arguments.length > 0 && arguments[0] ? arguments[0] : false;
  var deferAds = arguments.length > 1 && arguments[1] ? arguments[1] : true;
```

Having the field directly in the condition should be enough if we are checking if the value exists.

If we want to strictly check for `undefined`, we need to make use of `typeof`. The way it is written in the library is an anti pattern.

2021-05-17 11:55 UTC, EnKrypt commented on lib/idletimeout-shim.js
> +exports.getRequestIdleCallback = getRequestIdleCallback;
How are we using this?

2021-05-17 11:58 UTC, sivteck commented on lib/idletimeout-shim.js
> +exports.getRequestIdleCallback = getRequestIdleCallback;
lib/* files are build output from js/* files

2021-05-17 12:15 UTC, EnKrypt approved these changes

2021-05-18 03:49 UTC, Jeevan-Kishore approved these changes

2021-05-18 07:48 UTC, Harshith46 requested changes

2021-05-18 07:48 UTC, Harshith46 commented on js/utils.js
> +const delayGPTScriptLoadTimeBy = 2500;
why is this value hardcoded, can't this sent from the app level as config

2021-05-18 10:12 UTC, EnKrypt approved these changes

2021-05-24 05:33 UTC, Harshith46 approved these changes

2021-05-24 05:34 UTC, nandap4790 approved these changes

2021-05-24 08:29 UTC, merged